### ISSUE TITLE
Neo4jGraph.loadGraph issue : Neo4j session object leaked

### ISSUE THREAD

**Issue by sjishan** [neo4j-contrib/neo4j-spark-connector#14]
Hi, I was following the documentation to try neo4j-spark-connector and created a small graph with the same graph structure as provided in the example. I tried to load the graph however it is giving some error related to Neo4j session object leaked.

I am using spark 2.0 with scala 2.11.

Screenshot attached below. I will be thankful if you can address the issue. Thanks.

![capture](https://cloud.githubusercontent.com/assets/5510397/17457843/1557d40e-5bb8-11e6-8e61-f4bc18117c10.PNG)

**Comment by jexp** [comment]
Thanks for the note, I fixed it locally on another computer but have to push it.

**Comment by jexp** [comment]
Should be fixed now. Please try again. And reopen if the issue persists.

**Comment by annievic** [comment]
I am still getting the same error with neo4j-spark-connector version 2.0.0-M2?
